version: '3'

services: 
  db:
    image: mysql/mysql-server
    container_name: 'db'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
        - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: gzz123
      MYSQL_USER: gzz123
      MYSQL_PASSWORD: gzz123
    volumes:
      - /docker/mysql/init:/docker-entrypoint-initdb.d
      - /docker/mysql/config/my.cnf:/etc/my.cnf
      - /docker/mysql/data:/var/lib/mysql

  web:
    build: .
    container_name: 'userApi'
    ports:
      - '8888:80'
    depends_on:
      - db
